In [8]:
import numpy as np

arr1 = np.arange(1, 10, 2)
print (arr1)

arr2 = np.ones((3,4))
print(arr2)

arr3 = np.linspace(0, 1 ,11)
print(arr3)

[1 3 5 7 9]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [23]:
import numpy as np

A = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18 ,19, 20], [21, 22, 23, 24, 25]])
print(A.shape)
print(A[3,3])
print(A[:2, :2])
print(A[3:, 3:])

(5, 5)
19
[[1 2]
 [6 7]]
[[19 20]
 [24 25]]


In [30]:
A = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18 ,19, 20], [21, 22, 23, 24, 25]])
A_R = A.reshape()
print(A_R)
A_R.shape
A_R.size
B=A.reshape((3,4,3))


ValueError: cannot reshape array of size 25 into shape (3,3)